FROM ubi8/ubi:8.5

MAINTAINER Your Name <youremail>

ENV DOCROOT=/var/www/html

RUN yum install -y httpd && \
yum clean all

RUN echo "Hello World custom httpd" >> ${DOCROOT}/index.html

ONBUILD COPY src/ ${DOCROOT}/

EXPOSE 80

RUN rm -rf /run/httpd && mkdir /run/httpd

USER root

CMD ["httpd", "-D", "FOREGROUND"]

