apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd2
  name: httpd2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd2
  template:
    metadata:
      labels:
        app: httpd2
    spec:
      containers:
      - image: registry.ocp4.example.com:8443/ubi8/httpd-24:1-209 
        imagePullPolicy: IfNotPresent
        name: mydemo
        resources: 
          limits:
            cpu: "80m"
            memory: "100Mi"
      - image: ubi9 
        imagePullPolicy: IfNotPresent
        name: myubi
        command: ["/bin/sh", "-c"]
        args:
          - while true; do
              sleep 1;
            done
        resources:
          limits:
            cpu: "120m"
            memory: "140Mi"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
