apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "resource-limits"
spec:
  limits:
    - type: "Pod"
      max: 
        cpu: "500m"
        memory: "250Mi"
      min:
        cpu: "100m"
        memory: "50Mi"
    - type: "Container"
      max:
        cpu: "500m"
        memory: "250Mi"
      min:
        cpu: "100m"
        memory: "50Mi"
      default:
        cpu: "200m"
        memory: "100Mi"
      defaultRequest:
        cpu: "150m"
        memory: "70Mi"
