FROM registry.redhat.io/rhel9/nodejs-20:latest AS builder

WORKDIR /app
user root 

COPY package*.json ./

RUN npm install

COPY . .

# -------- Stage 2 : Runtime stage ----------
FROM registry.redhat.io/ubi9/nodejs-20-minimal:9.7
WORKDIR /app
COPY --from=builder /app /app
user 1001
EXPOSE 3000
CMD ["npm", "start"]
