apiVersion:  kind.x-k8s.io/v1alpha4
kind: Cluster
# patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta3
  kind: ClusterConfiguration
  metadata:
    name: config
  kubernetesVersion: "v@KUBERNETES_VERSION@"
  networking:
    serviceSubnet: 10.0.0.0/16
nodes:
- role: control-plane
  extraMounts:
    - containerPath: /var/lib/kubelet
      hostPath: "@TMPDIR@/controller"
      propagation: Bidirectional
- role: worker
  extraMounts:
    - containerPath: /run/topolvm
      hostPath: "@TMPDIR@/lvmd"
    - containerPath: /var/lib/kubelet
      hostPath: "@TMPDIR@/worker"
      propagation: Bidirectional
    - containerPath: /dev
      hostPath: /dev
