FROM registry.access.redhat.com/ubi8/nodejs-14:1 AS build
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM node:18-alpine
WORKDIR /app

COPY --from=build /app/dist ./dist
COPY package*.json ./

RUN npm install --production

CMD ["node", "dist/app.js"]
