apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc001
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
      #  storageClassName: lvms-vg1
      #  volumeMode: Filesystem
      #  volumeName: pvc-d10131cf-1da2-4e3f-97d5-93798ae2d221
