apiVersion: operator.openshift.io/v1
kind: ClusterCSIDriver
metadata:
  annotations:
    storage.openshift.io/remove-from: mgmt
  name: ebs.csi.aws.com
  namespace: openshift-cluster-csi-drivers
spec:
  logLevel: Normal
  managementState: Managed
  operatorLogLevel: Normal
