apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-lvm-2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: topolvm-provisioner









