apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web2
  name: web2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web2
  template:
    metadata:
      labels:
        app: web2
    spec:
      containers:
      - image: quay.io/ravindra_be2004/mydemo:v1
              #      - image: registry.access.redhat.com/ubi9/httpd-24
        imagePullPolicy: IfNotPresent
        name: mydemo
        resources:
          requests:
            cpu: "100m"
            memory: "1Gi"
          limits:
            cpu: "200m"
            memory: "2Gi"
