FROM ubi8/ubi:8.5

MAINTAINER Your Name <youremail>

LABEL io.k8s.description="Apache server child image,uses ONBUILD" \
      io.k8s.display-name="Apache http server" \
      io.openshift.expose-services="8080:http" \
      io.openshift.tags="apache, httpd"


ENV DOCROOT=/var/www/html

RUN yum install -y httpd && \
yum clean all

RUN echo "Hello World custom httpd" >> ${DOCROOT}/index.html

EXPOSE 8080

RUN rm -rf /run/httpd && mkdir /run/httpd

RUN sed -i "s/Listen 80/Listen 8080/g" /etc/httpd/conf/httpd.conf

RUN sed -i "s/#ServerName www.example.com:80/ServerName 0.0.0.0:8080/g" /etc/httpd/conf/httpd.conf

RUN chgrp -R 0 /var/log/httpd /var/run/httpd && \
chmod -R g=u /var/log/httpd /var/run/httpd

USER 1001

CMD ["httpd", "-D", "FOREGROUND"]

